spring:
  application:
    name: spring-clock-example

  clock:
    # timezone-id: Asia/Tokyo
    timezone-id: Europe/London
    # timezone-id: EST

logging:
  level:
    xyz.walk8243.springframework.clock: DEBUG
