name: Publish Gradle Package

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Set package version
        run: echo "PACKAGE_VERSION=${RELEASE_VERSION#v}" >> "$GITHUB_ENV"
      - name: Publish Gradle Package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
