name: Publish Gradle Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Publish Gradle Package
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
